[2025-01-07 22:03:27,330] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:27,330] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:03:27,330] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:27,330] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:27,330] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:27,330] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:27,330] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:28,165] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:28,328] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:28,328] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:28,329] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:28,330] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:03:28,374] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:28,375] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:29,213] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:29,261] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:29,308] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:29,332] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:29,363] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:29,375] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:29,381] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:03:30,145] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:30,162] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:30,226] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:30,253] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:30,298] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:30,344] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:30,445] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:03:31,043] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:31,086] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:31,160] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:31,255] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:31,258] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:31,330] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:31,530] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:03:31,972] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:32,009] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:32,046] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:32,189] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:03:32,239] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:03:32,332] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:21,109] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:21,110] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:21,110] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:21,110] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:21,110] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:21,109] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:21,109] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:21,964] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:22,017] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:22,075] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:321)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:515)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:272)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:22,108] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:22,109] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:22,108] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:22,124] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:22,847] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:23,040] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:23,040] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:23,049] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:23,095] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:23,111] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:23,111] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:23,731] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:23,868] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:23,995] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:24,044] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:24,087] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:24,096] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:24,108] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:24,716] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:24,730] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:24,880] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:24,978] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:25,097] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:25,126] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:25,163] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:25,692] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:25,732] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:25,813] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:26,005] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:26,017] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:26,105] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:321)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.trySend(ConsumerNetworkClient.java:515)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:272)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:26,136] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:26,571] WARN [Producer clientId=connect-cluster-offsets] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:26,734] WARN [Producer clientId=connect-cluster-statuses] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:26,805] WARN [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:26,993] WARN [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:27,013] WARN [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1340)
	at org.apache.kafka.clients.NetworkClient$TelemetrySender.maybeUpdate(NetworkClient.java:1309)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:594)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:253)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:244)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.awaitMetadataUpdate(ConsumerNetworkClient.java:166)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:527)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.updateAssignmentMetadataIfNeeded(ClassicKafkaConsumer.java:657)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:616)
	at org.apache.kafka.clients.consumer.internals.ClassicKafkaConsumer.poll(ClassicKafkaConsumer.java:596)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:874)
	at org.apache.kafka.connect.util.KafkaBasedLog.poll(KafkaBasedLog.java:471)
	at org.apache.kafka.connect.util.KafkaBasedLog.access$500(KafkaBasedLog.java:86)
	at org.apache.kafka.connect.util.KafkaBasedLog$WorkThread.run(KafkaBasedLog.java:612)
[2025-01-07 22:04:27,053] WARN [Producer clientId=connect-cluster-configs] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:349)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:251)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:04:27,165] WARN [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Network is unreachable
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.access$800(NetworkClient.java:77)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1264)
	at org.apache.kafka.clients.NetworkClient$DefaultMetadataUpdater.maybeUpdate(NetworkClient.java:1164)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:593)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:282)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.pollNoWakeup(ConsumerNetworkClient.java:323)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator$HeartbeatThread.run(AbstractCoordinator.java:1501)
[2025-01-07 22:04:38,620] INFO [mariadb-connector|worker] Completed shutdown for WorkerConnector{id=mariadb-connector} (org.apache.kafka.connect.runtime.WorkerConnector:315)
[2025-01-07 22:04:38,620] INFO [mongodb-sink-connector|worker] Completed shutdown for WorkerConnector{id=mongodb-sink-connector} (org.apache.kafka.connect.runtime.WorkerConnector:315)
[2025-01-07 22:21:59,333] INFO [Producer clientId=connect-cluster-offsets] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 29460 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:21:59,334] INFO [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 27599 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:21:59,334] INFO [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 30000 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:21:59,333] INFO [Producer clientId=connect-cluster-configs] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 29941 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:21:59,333] INFO [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 30000 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:21:59,333] INFO [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 25653 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:21:59,466] INFO [Producer clientId=connect-cluster-statuses] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 30000 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,344] INFO [Producer clientId=connect-cluster-statuses] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 26850 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,363] INFO [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 29118 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,344] INFO [Producer clientId=connect-cluster-offsets] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 24566 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,344] INFO [Producer clientId=connect-cluster-configs] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 26274 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,344] INFO [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 30000 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,344] INFO [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 28403 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:39:11,344] INFO [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 30000 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Consumer clientId=connect-cluster-statuses, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 24396 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Producer clientId=connect-cluster-offsets] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 24475 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Consumer clientId=connect-cluster-offsets, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 27858 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Worker clientId=connect-192.168.1.5:8083, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 25982 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Consumer clientId=connect-cluster-configs, groupId=connect-cluster] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 29888 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Producer clientId=connect-cluster-statuses] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 30000 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,242] INFO [Producer clientId=connect-cluster-configs] Disconnecting from node 0 due to socket connection setup timeout. The timeout value is 28291 ms. (org.apache.kafka.clients.NetworkClient:893)
[2025-01-07 22:57:29,644] WARN [AdminClient clientId=connect-cluster-shared-admin] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Host is down
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:321)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:1270)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1530)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1473)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:57:29,765] WARN [AdminClient clientId=connect-cluster-shared-admin] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Host is down
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:321)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:1270)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1530)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1473)
	at java.base/java.lang.Thread.run(Thread.java:1575)
[2025-01-07 22:57:29,944] WARN [AdminClient clientId=connect-cluster-shared-admin] Error connecting to node 192.168.1.5:9092 (id: 0 rack: null) (org.apache.kafka.clients.NetworkClient:1082)
java.net.SocketException: Host is down
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:596)
	at java.base/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:968)
	at org.apache.kafka.common.network.Selector.doConnect(Selector.java:293)
	at org.apache.kafka.common.network.Selector.connect(Selector.java:271)
	at org.apache.kafka.clients.NetworkClient.initiateConnect(NetworkClient.java:1077)
	at org.apache.kafka.clients.NetworkClient.ready(NetworkClient.java:321)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.sendEligibleCalls(KafkaAdminClient.java:1270)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.processRequests(KafkaAdminClient.java:1530)
	at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1473)
	at java.base/java.lang.Thread.run(Thread.java:1575)
